openapi: 3.0.0
info:
  title: Ethel AI API
  description: Documentacion para consumir los servicios de Ethel AI
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server

paths:
  /v1/ethel-ia/full/procesar-consulta:
    post:
      summary: Procesamiento de consulta con Ethel AI
      description: Realiza el procesamiento completo de una consulta utilizando el modelo Ethel AI. 
      tags:
        - EthelAI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pregunta:
                  type: string
        responses:
          '200': 
            description: La respuesta a la consulta hecha a la AI
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    type: string
          '401': 
            description: No esta autorizado para consumir la API
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    type: string